# Generated by Django 5.2.15 on 2026-07-01 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Ícone (emoji)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nome do cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('customer_address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('customer_complement', models.CharField(blank=True, max_length=200, verbose_name='Complemento')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Retirada')], default='delivery', max_length=10, verbose_name='Tipo')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Observações')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Taxa de entrega')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Pagamento'), ('confirmed', 'Pagamento Confirmado'), ('preparing', 'Preparando'), ('out_for_delivery', 'Saiu para Entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('pix_code', models.TextField(blank=True, verbose_name='Código PIX copia e cola')),
                ('pix_proof', models.ImageField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante PIX')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Comissão (2%)')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Comissão paga')),
                ('commission_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Comissão paga em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Foto')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'verbose_name': 'Item do cardápio',
                'verbose_name_plural': 'Itens do cardápio',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Item')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço unitário')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do restaurante')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Link do cardápio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('pix_key', models.CharField(blank=True, max_length=200, verbose_name='Chave PIX')),
                ('pix_key_type', models.CharField(choices=[('phone', 'Telefone'), ('email', 'E-mail'), ('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('random', 'Chave Aleatória')], default='phone', max_length=20, verbose_name='Tipo de chave PIX')),
                ('merchant_name', models.CharField(blank=True, max_length=25, verbose_name='Nome no PIX')),
                ('merchant_city', models.CharField(default='Arroio do Sal', max_length=15, verbose_name='Cidade no PIX')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Taxa de entrega')),
                ('min_order', models.DecimalField(decimal_places=2, default=15.0, max_digits=6, verbose_name='Pedido mínimo')),
                ('is_open', models.BooleanField(default=True, verbose_name='Aberto')),
                ('opening_time', models.TimeField(default='18:00', verbose_name='Abre às')),
                ('closing_time', models.TimeField(default='23:00', verbose_name='Fecha às')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('delivery_info', models.TextField(blank=True, verbose_name='Informações de entrega')),
                ('plan', models.CharField(choices=[('trial', 'Trial 14 dias'), ('basic', 'Básico - R$ 97/mês'), ('pro', 'Pro - R$ 197/mês')], default='trial', max_length=10, verbose_name='Plano')),
                ('trial_start', models.DateField(default=django.utils.timezone.now, verbose_name='Início do trial')),
                ('plan_start', models.DateField(blank=True, null=True, verbose_name='Início do plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Comissão (%)')),
                ('commission_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comissão acumulada a pagar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.restaurant'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_record', to='menu.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='menu.restaurant')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant'),
        ),
    ]
