# Generated by Django 5.2.15 on 2026-07-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Taxa de configuração'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial 14 dias'), ('basic', 'Básico - R$ 195/mês'), ('pro', 'Pro - R$ 470/mês')], default='trial', max_length=10, verbose_name='Plano'),
        ),
    ]
