# Generated by Django 5.2.15 on 2026-07-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restaurant_setup_fee_alter_restaurant_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Comissão (5%)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Comissão (%)'),
        ),
    ]
