# Generated by Django 5.2.15 on 2026-07-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_order_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial 14 dias'), ('basic', 'Básico - R$ 195/mês'), ('pro', 'Pro - R$ 395/mês')], default='trial', max_length=10, verbose_name='Plano'),
        ),
    ]
