# Generated by Django 5.2.15 on 2026-07-01 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_customerprofile_order_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro padrão'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bairro / Região')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Taxa de entrega')),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Pedido mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='menu.restaurant')),
            ],
            options={
                'verbose_name': 'Zona de Entrega',
                'verbose_name_plural': 'Zonas de Entrega',
                'ordering': ['order', 'name'],
            },
        ),
    ]
